module.exports = {
  company: 'Company',
  contact: 'Company contact',
  service: 'Service',
  status: 'Status',
  subject: 'Subject',
  notes: 'Notes',
  date: 'Service delivery start date',
  dit_team: 'Service provider',
  dit_adviser: 'DIT adviser',
  uk_region: 'UK region',
  sector: 'Sector',
  country_of_interest: 'Country of interest',
  event: 'Event',
}
