version: '3'
services:
  frontend:
    image: gcr.io/sre-docker-registry/data-hub-frontend-functional:${CIRCLE_SHA1}
    depends_on:
      - redis
    volumes:
      - ./:/usr/src/app:delegated
      # Ensures that the local node_modules dir is not used in the container
      - /usr/src/app/node_modules
    ports:
      - ${PORT:-3000}:3000
      - 9229:9229
    env_file: .env
    user: "${CURRENT_UID}:${CURRENT_GID}"
    environment:
      API_ROOT: ${API_ROOT}
      # Required to test Data Hub roles in e2e tests, make sure this var
      # doesn't exists in your .env file as the override below won't work
      OAUTH2_DEV_TOKEN: ${OAUTH2_DEV_TOKEN:-ditStaffToken}
      CURRENT_UID: ${CURRENT_UID}
      CURRENT_GID: ${CURRENT_GID}
    command: npm run develop

  redis:
    image: redis:6.2.6
