version: '3'

services:
  mock-third-party-services:
    build: ./test/sandbox
    environment:
      SANDBOX_PORT: 8888
    volumes:
      - ./test/sandbox:/usr/src/app
      # Ensures that the local node_modules dir is not used in the container
      - /usr/src/app/node_modules
    logging:
      driver: none

  lbweb:
    image: gcr.io/sre-docker-registry/github.com/uktrade/legal-basis-api:latest
    environment:
      DJANGO_DATABASE_HOST: db
      DJANGO_ENV: test
      DJANGO_SECRET_KEY: 4c1nzrs&8^g+t$tt**wl7u8)0p8ql3vr28rjn1mdcnr*crjz*#
      DATABASE_URL: postgres://postgres@lbdb:5432/legal-basis
      DJANGO_SETTINGS_MODULE: server.settings
      AUTHBROKER_URL: https://sso.trade.gov.uk/
      AUTHBROKER_CLIENT_ID: client_id
      AUTHBROKER_CLIENT_SECRET: client_secret
      DOMAIN_NAME: lbweb
      TLS_EMAIL: webmaster@trade.gov.uk
      ACTIVITY_STREAM_URL: https://localhost/v3/
      ACTIVITY_STREAM_ID: fake_id
      ACTIVITY_STREAM_KEY: fake_key
      REDIS_URL: redis://redis/
      MAXEMAIL_BASE_URL: dummyURL
      MAXEMAIL_USERNAME: dummyUser
      MAXEMAIL_PASSWORD: dummyPassword
      ELASTIC_APM_DISABLE_SEND: 1
      DYNAMICS_INSTANCE_URI: https://localhost
      DYNAMICS_TENANT_ID: xxx
      DYNAMICS_APPLICATION_ID: xxx
      DYNAMICS_CLIENT_SECRET: xxx
    ports:
      - 8001:8001
    depends_on:
      - lbdb
    command: >
      bash -c "sleep 5 && python manage.py migrate && python manage.py collectstatic --noinput && python -Wd manage.py runserver 0.0.0.0:8001"

  lbdb:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: legal-basis
      POSTGRES_PASSWORD: password
