version: '3'
services:
  frontend:
    platform: linux/amd64
    build:
      context: .
      args:
        CURRENT_UID: ${CURRENT_UID}
        CURRENT_GID: ${CURRENT_GID}
    depends_on:
      - redis
    volumes:
      - ./:/usr/src/app:delegated
      # Ensures that the local node_modules dir is not used in the container
      - /usr/src/app/node_modules
    ports:
      - ${PORT:-3000}:3000
      - 9229:9229
    env_file: .env
    user: "${CURRENT_UID}:${CURRENT_GID}"
    environment:
      API_ROOT: ${API_ROOT}
      # Required to test Data Hub roles in e2e tests, make sure this var
      # doesn't exists in your .env file as the override below won't work
      OAUTH2_DEV_TOKEN: ${OAUTH2_DEV_TOKEN:-ditStaffToken}
      NODE_ENV: test
    command: bash -c 'npm run build:for-test-coverage && npm run start:coverage'
  redis:
    image: redis:7.2.4
