export const ID = 'interactionDetailsForm'

export const TASK_SAVE_INTERACTION = 'TASK_SAVE_INTERACTION'
export const TASK_OPEN_CONTACT_FORM = 'TASK_OPEN_CONTACT_FORM'
export const TASK_ACTIVE_EVENTS = 'TASK_ACTIVE_EVENTS'
