module.exports = {
  eventNameId: '#name',
  eventTypeFieldId: '#field-event_type',
  startDateId: '#start_date',
  endDateId: '#end_date',
  locationTypeFieldId: '#field-location_type',
  addressLine1Id: '#address_1',
  addressLine2Id: '#address_2',
  addressTownId: '#address_town',
  addressPostcodeId: '#address_postcode',
  addressCountryId: '#address_county',
  addressCountryFieldId: '#field-address_country',
  ukRegionFieldId: '#field-uk_region',
  ukRegionId: '#uk_region',
  notesId: '#notes',
  serviceFieldId: '#field-service',
  leadTeamFieldId: '#field-lead_team',
  organiserFieldId: '#field-organiser',
  eventShared: '[name = "event_shared"]',
  teamsFieldId: '#field-teams',
  teamsId: '#teams',
  relatedProgrammesFieldId: '#field-related_programmes',
  relatedTradeAgreements: '[name="has_related_trade_agreements"]',
  relatedTradeAgreementsFieldId: '#field-related_trade_agreements',
}
