module.exports = {
  add: '[data-auto-id="Add event"]',
  eventName: '#field-name',
  nameError: 'label[for=field-name] span:nth-child(2)',
  eventType: 'select[name="event_type"]',
  typeError: 'label[for=field-event_type] span:nth-child(2)',
  startDateYear: 'input[name="start_date_year"]',
  startDateMonth: 'input[name="start_date_month"]',
  startDateDay: 'input[name="start_date_day"]',
  startDateError: '#group-field-start_date span:nth-child(2)',
  endDateYear: 'input[name="end_date_year"]',
  endDateMonth: 'input[name="end_date_month"]',
  endDateDay: 'input[name="end_date_day"]',
  endDateError: '#group-field-end_date span:nth-child(2)',
  locationType: 'select[name="location_type"]',
  addressLine1: 'input[name="address_1"]',
  addressLine1Error: 'label[for=field-address_1] span:nth-child(2)',
  addressLine2: 'input[name="address_2"]',
  addressTown: 'input[name="address_town"]',
  addressTownError: 'label[for=field-address_town] span:nth-child(2)',
  addressCounty: 'input[name="address_county"]',
  addressPostcode: 'input[name="postcode"]',
  addressCountry: 'select[name="address_country"]',
  addressCountryError: 'label[for=field-address_country] span:nth-child(2)',
  ukRegion: 'select[name="uk_region"]',
  ukRegionError: 'label[for=field-uk_region] span:nth-child(2)',
  notes: 'textarea[name="notes"]',
  service: 'select[name="service"]',
  serviceError: 'label[for=field-service] span:nth-child(2)',
  leadTeam: 'select[name="lead_team"]',
  organiserError: '#organiser-error-messages',
  organiser: '.multiselect__tags',
  organiserInput: '.multiselect__input',
  organiserOption: '.multiselect__option-label',
  sharedYes: 'label[for=field-event_shared-1]',
  sharedNo: 'label[for=field-event_shared-2]',
  teams: '[name="teams"]',
  addAnotherSharedTeam: 'input[name="add_team"]',
  relatedProgrammes: '[name="related_programmes"]',
  addAnotherProgramme: 'input[name="add_related_programme"]',
  saveEvent: 'button:contains("Add event")',
  saveAndReturn: 'button:contains("Save and return")',
  relatedTradeAgreements: '[name="related_trade_agreements"]',
  addAnotherTradeAgreement: 'input[name="add_related_trade_agreement"]',
  tradeAgreementExistsYes:
    'label[for="field-related_trade_agreements_exist-1"]',
}
