version: 0.2

run-as: root

env:
  shell: bash
  variables:
    CI: 'True'
  parameter-store:
    CYPRESS_DASHBOARD_KEY: /codebuild/datahub/datahub-fe/test/CYPRESS_DASHBOARD_KEY
    POSTCODE_KEY: /codebuild/datahub/datahub-fe/test/POSTCODE_KEY

phases:
  pre_build:
    commands:
      - cp sample.env .env
      - make start-mock

  build:
    commands:
      - make functional-tests

  post_build:
    commands:
      # -
