export const TASK_EDIT_OMIS_QUOTE_INFORMATION =
  'TASK_EDIT_OMIS_QUOTE_INFORMATION'
export const TASK_EDIT_OMIS_INTERNAL_INFORMATION =
  'TASK_EDIT_OMIS_INTERNAL_INFORMATION'
export const TASK_RECONCILE_OMIS_PAYMENT = 'TASK_RECONCILE_OMIS_PAYMENT'

export const state2props = (state) => ({
  csrfToken: state.csrfToken,
})
