module.exports = {
  url: process.env.QA_HOST,
  props: {},
  elements: {
    eventName: 'a',
    eventType: 'a',
    eventTypeList: 'a',
    additionalRefCode: 'a',
    startDate: 'a',
    endDate: 'a',
    locationType: 'a',
    addressLine1: 'a',
    addressLine2: 'a',
    addressTown: 'a',
    addressPostcode: 'a',
    addressCountry: 'a',
    notes: 'a',
    teamHosting: 'a',
    organiser: 'a',
    sharedYes: 'a',
    sharedNo: 'a',
    sharedTeams: 'a',
    sharedTeamsList: 'a',
    addTeamToList: 'a',
    addAnotherTeam: 'a',
    relatedProgrammes: 'a',
    relatedProgrammesList: 'a',
    saveButton: 'a',

    // Event details page
    eventNameFromDetails: 'a',
    eventTypeFromDetails: 'a',
    additionalRefCodeFromDetails: 'a',
    startDateFromDetails: 'a',
    endDateFromDetails: 'a',
    locationTypeFromDetails: 'a',
    addressLine1FromDetails: 'a',
    addressLine2FromDetails: 'a',
    addressTownFromDetails: 'a',
    addressPostcodeFromDetails: 'a',
    addressCountryFromDetails: 'a',
    notesFromDetails: 'a',
    teamHostingFromDetails: 'a',
    organiserFromDetails: 'a',
    sharedYesFromDetails: 'a',
    sharedTeamsFromDetails: 'a',
    relatedProgrammesFromDetails: 'a',
  },

  commands: [
    {
    },
  ],
}
