const typeaheadID = '#group-field-dit_participants'

module.exports = {
  subject: '#field-subject',
  notes: '#field-notes',
  dateOfInteractionYear: '#field-date_year',
  dateOfInteractionMonth: '#field-date_month',
  dateOfInteractionDay: '#field-date_day',
  contact: '#field-contacts',
  add: 'form > div.c-form-actions > button',
  service: '#field-service',
  serviceDeliveryStatus: '#field-service_delivery_status',
  subService: '#field-subService',
  grantOffered: '#field-grant_amount_offered',
  netReceipt: '#field-net_company_receipt',
  ditAdviserTypeahead: {
    fieldset: typeaheadID,
    placeHolder: `${typeaheadID} .multiselect__input`,
    textInput: `${typeaheadID} .multiselect__tags`,
    selectedOption: `${typeaheadID} .multiselect__single`,
    addAnotherBtn: `${typeaheadID} .js-AddItems__add--typeahead`,
    secondTypeahead: `${typeaheadID} .c-form-group__inner .c-form-group--AddItems:nth-child(2) .multiselect__input`,
    secondTypeaheadRemoveLink: `${typeaheadID} .c-form-group__inner .c-form-group--AddItems:nth-child(2) .js-AddItems__remove`,
  },
  communicationChannel: '#field-communication_channel',
  eventYes: 'label[for=field-is_event-1]',
  eventNo: 'label[for=field-is_event-2]',
  event: '#field-event',
  policyFeedbackYes: 'label[for=field-was_policy_feedback_provided-1]',
  policyFeedbackNo: 'label[for=field-was_policy_feedback_provided-2]',
  policyIssueType1: 'label[for=field-policy_issue_types-1]',
  policyIssueType2: 'label[for=field-policy_issue_types-2]',
  policyIssueType3: 'label[for=field-policy_issue_types-3]',
  policyIssueType4: 'label[for=field-policy_issue_types-4]',
  policyIssueType5: 'label[for=field-policy_issue_types-5]',
  policyArea: '#field-policy_areas',
  policyFeedbackNotes: '#field-policy_feedback_notes',
  teamSearch: '#dit_team__typeahead .multiselect__single',
}
