const interactions = {
  subject: '#field-subject',
  notes: '#field-notes',
  dateOfInteractionYear: '#field-date_year',
  dateOfInteractionMonth: '#field-date_month',
  dateOfInteractionDay: '#field-date_day',
  contact: '#field-contact',
  serviceProvider: '#field-dit_team',
  service: '#field-service',
  serviceStatus: '#field-service_delivery_status',
  grantOffered: '#field-grant_amount_offered',
  netReceipt: '#field-net_company_receipt',
  ditAdviser: '#dit_adviser__typeahead .multiselect__single',
  communicationChannel: '#field-communication_channel',
  eventYes: 'label[for=field-is_event-1]',
  eventNo: 'label[for=field-is_event-2]',
  event: '#field-event',
  policyFeedbackYes: 'label[for=field-was_policy_feedback_provided-1]',
  policyFeedbackNo: 'label[for=field-was_policy_feedback_provided-2]',
  policyIssueType1: 'label[for=field-policy_issue_types-1]',
  policyIssueType2: 'label[for=field-policy_issue_types-2]',
  policyIssueType3: 'label[for=field-policy_issue_types-3]',
  policyIssueType4: 'label[for=field-policy_issue_types-4]',
  policyIssueType5: 'label[for=field-policy_issue_types-5]',
  policyArea: '#field-policy_areas',
  policyFeedbackNotes: '#field-policy_feedback_notes',
  teamSearch: '#dit_team__typeahead .multiselect__single',
}

export default interactions
