export const TASK_CREATE_INVESTMENT_PROPOSITION =
  'TASK_CREATE_INVESTMENT_PROPOSITION'
export const TASK_ABANDON_INVESTMENT_PROPOSITION =
  'TASK_ABANDON_INVESTMENT_PROPOSITION'

export const DELETE_PROPOSITION_DOCUMENT_ID =
  'deleteInvestmentPropositionDocument'
export const TASK_DELETE_PROPOSITION_DOCUMENT =
  'TASK_DELETE_PROPOSITION_DOCUMENT'

export const TASK_ADD_PROPOSITION_DOCUMENT = 'TASK_ADD_PROPOSITION_DOCUMENT'
