export const HEADQUARTER_TYPE = 'Type'
export const COMPANY_NAME = 'Company Name'
export const SECTOR = 'Sector'
export const COUNTRY = 'Country'
export const UK_REGION = 'UK Region'
export const COMPANY_STATUS = 'Status'
export const CURRENTLY_EXPORTING_TO = 'Currently exporting to'
export const FUTURE_COUNTRIES_OF_INTEREST = 'Future country of interest'
