module.exports = {
  name: '[data-test="field-name"]',
  description: '[data-test="field-description"]',
  anonymousDescription: '[data-test="field-anonymous_description"]',
  primarySector: '[data-test="field-sector"]',
  businessActivities: '[data-test="field-business_activities"]',
  clientContact: '[data-test="field-client_contacts"]',
  clientRelationshipManagerYes: '[data-test="client-relationship-manager-yes"]',
  referralSourceYes: '[data-test="is-referral-source-yes"]',
  referralSourceActivity: '#referral_source_activity',
  estimatedLandDateYear: '[data-test="estimated_land_date-year"]',
  estimatedLandDateMonth: '[data-test="estimated_land_date-month"]',
  actualLandDateYear: '[data-test="actual_land_date-year"]',
  actualLandDateMonth: '[data-test="actual_land_date-month"]',
  actualLandDateDay: '[data-test="actual_land_date-day"]',
  investorTypeNew: '[data-test="investor-type-new-investor"]',
  levelOfInvolvement: '[data-test="field-level_of_involvement"]',
  specificInvestmentProgrammes: '[data-test="field-specific_programmes"]',
  submitButton: '[data-test="submit"]',
}
