module.exports = {
  name: '[data-test="field-name"]',
  description: '[data-test="field-description"]',
  anonymousDescription: '[data-test="field-anonymous_description"]',
  primarySector: '[data-test="field-sector"]',
  businessActivities: '[data-test="field-business_activities"]',
  otherBusinessActivity: '[data-test="field-other_business_activity"]',
  clientContact: '[data-test="field-client_contacts"]',
  clientRelationshipManager: '[data-test="field-client_relationship_manager"]',
  clientRelationshipManagerYes: '[data-test="client-relationship-manager-yes"]',
  clientRelationshipManagerNo: '[data-test="client-relationship-manager-no"]',
  referralSource: '[data-test="field-is_referral_source"]',
  referralSourceYes: '[data-test="is-referral-source-yes"]',
  referralSourceNo: '[data-test="is-referral-source-no"]',
  referralSourceActivity: '#referral_source_activity',
  referralSourceActivityEvent:
    '[data-test="field-referral_source_activity_event"]',
  referralSourceActivityMarketing:
    '[data-test="field-referral_source_activity_marketing"]',
  referralSourceActivityWebsite:
    '[data-test="field-referral_source_activity_website"]',
  estimatedLandDateYear: '[data-test="estimated_land_date-year"]',
  estimatedLandDateMonth: '[data-test="estimated_land_date-month"]',
  actualLandDateYear: '[data-test="actual_land_date-year"]',
  actualLandDateMonth: '[data-test="actual_land_date-month"]',
  actualLandDateDay: '[data-test="actual_land_date-day"]',
  investorType: '[data-test="investor_type"]',
  investorTypeExisting: '[data-test="investor-type-existing-investor"]',
  investorTypeNew: '[data-test="investor-type-new-investor"]',
  levelOfInvolvement: '[data-test="field-level_of_involvement"]',
  specificInvestmentProgramme: '[data-test="field-specific_programme"]',
  submitButton: '[data-test="submit"]',
  history: '#investment-edit-history',
}
