module.exports = {
  name: '[data-test="name"]',
  description: '[data-test="description"]',
  anonymousDescription: '[data-test="anonymous-description"]',
  primarySector: '[data-test="primary-sector"]',
  businessActivities: '[data-test="business-activities"]',
  otherBusinessActivity: '[data-test="other-business-activity"]',
  clientContact: '[data-test="client-contact"]',
  clientRelationshipManager: '[data-test="client-relationship-manager"]',
  clientRelationshipManagerYes: '[data-test="client-relationship-manager-yes"]',
  clientRelationshipManagerNo: '[data-test="client-relationship-manager-no"]',
  referralSource: '[data-test="referral-source-adviser"]',
  referralSourceYes: '[data-test="referral-source-adviser-yes"]',
  referralSourceNo: '[data-test="referral-source-adviser-no"]',
  referralSourceActivity: '[data-test="referral-source-activity"]',
  referralSourceActivityEvent: '[data-test="referral-source-activity-event"]',
  referralSourceActivityMarketing:
    '[data-test="referral-source-activity-marketing"]',
  referralSourceActivityWebsite:
    '[data-test="referral-source-activity-website"]',
  estimatedLandDateYear: '[data-test="estimated-land-date-year"]',
  estimatedLandDateMonth: '[data-test="estimated-land-date-month"]',
  actualLandDateYear: '[data-test="actual-land-date-year"]',
  actualLandDateMonth: '[data-test="actual-land-date-month"]',
  actualLandDateDay: '[data-test="actual-land-date-day"]',
  investorType: '[data-test="investor-type"]',
  levelOfInvolvement: '[data-test="level-of-involvement"]',
  specificInvestmentProgramme: '[data-test="specific-investment-programme"]',
  submitButton: '[data-test="submit"]',
  history: '#investment-edit-history',
}
