module.exports = {
  flash: '[data-test="flash"]',
  removeMethod: '[data-method="remove"]',
  addTypeahead: '[data-method="add-typeahead"]',
  clientRelationship: {
    button: '[data-test="client-relationship-management-button"]',
    header: '[data-test="client-relationship-header"]',
    typeahead: '[data-typeahead-type="client_relationship_manager"]',
    globalSummary: '[data-test="global-account-manager-summary"]',
    globalContents: '[data-test="global-account-manager-contents"]',
    save: '[data-test="client-relationship-management-save"]',
    table: '[data-test="client-relationship-management-content"]',
  },
  projectManagement: {
    button: '[data-test="project-management-button"]',
    header: '[data-test="assign-project-management-heading"]',
    projectInfo: '[data-test="project-management-table"]',
    assuranceTypeahead: '[data-typeahead-type="project_assurance_adviser"]',
    pmTypeahead: '[data-typeahead-type="project_manager"]',
    save: '[data-test="project-management-save"]',
    table: '[data-test="project-management-content"]',
  },
  teamMembers: {
    button: '[data-test="project-specialist-team-members-button"]',
    header: '[data-test="assign-team-members-header"]',
    typeahead: '[data-typeahead-type="adviser"]',
    teamRole: '[data-test="team-role"]',
    save: '[data-test="team-members-save"]',
    table: '[data-test="project-specialist-team-members-content"]',
  },
}
