module.exports = {
  totalInvestmentRadioYes: '[for="field-client_cannot_provide_total_investment-1"]',
  totalInvestmentRadioNo: '[for="field-client_cannot_provide_total_investment-2"]',
  totalInvestment: '#field-total_investment',
  foreignEquityInvestmentRadioYes: '[for="field-client_cannot_provide_foreign_investment-1"]',
  foreignEquityInvestmentRadioNo: '[for="field-client_cannot_provide_foreign_investment-2"]',
  foreignEquityInvestment: '#field-foreign_equity_investment',
  newJobs: '#field-number_new_jobs',
  safeguardedJobs: '#field-number_safeguarded_jobs',
  governmentAssistanceRadioYes: '[for="field-government_assistance-1"]',
  governmentAssistanceRadioNo: '[for="field-government_assistance-2"]',
  rDBudgetRadioYes: '[for="field-r_and_d_budget-1"]',
  rDBudgetRadioNo: '[for="field-r_and_d_budget-2"]',
  nonFdiRDProjectRadioYes: '[for="field-non_fdi_r_and_d_budget-1"]',
  nonFdiRDProjectRadioNo: '[for="field-non_fdi_r_and_d_budget-2"]',
  newToWorldTechRadioYes: '[for="field-new_tech_to_uk-1"]',
  newToWorldTechRadioNo: '[for="field-new_tech_to_uk-2"]',
  exportRevenueRadioYes: '[for="field-export_revenue-1"]',
  exportRevenueRadioNo: '[for="field-export_revenue-2"]',
  save: '.c-form-actions > button',
}
