// 'alphabetical', 'recent', 'least-recent'
export const ALPHABETICAL = 'alphabetical'
export const RECENT = 'recent'
export const LEAST_RECENT = 'least-recent'
export const UNKNOWN_ADVISER = 'unknown adviser'
export const UNKNOWN_TEAM = 'unknown team'
export const MULTIPLE_ADVISERS = 'Multiple advisers'
