export const urlTestExclusions = [
  // A11y errors
  { url: '/investment-projects/' },
  { url: '/companies/:companyId/edit-history' },
  { url: '/companies/:companyId/exports' },
  { url: '/exportwins/' },
  { url: '/companies/:companyId/investments/large-capital-profile' },
  { url: '/companies/:companyId/account-management' },
  { url: '/events/:eventId/attendees/find-new' },
  { url: '/companies/:companyId/interactions/create' },
  { url: '/companies/:companyId/interactions' },
  { url: '/companies/:companyId/hierarchies/ghq/search' },
  { url: '/search/' },
  { url: '/search/:searchPath?' },
  { url: '/tasks/:taskId/edit' },
  { url: '/companies/:companyId/overview' },
  // 404 errors and or no sandbox data available
  { url: '/companies/:companyId/audit' },
  { url: '/companies/:companyId/archive' },
  { url: '/companies/:companyId/unarchive' },
  { url: '/companies/:companyId/lists' },
  { url: '/companies/:companyId/manage-company-list' },
  { url: '/v4/dnb/:companyId/related-companies/count' },
  { url: '/company-lists/:listId/delete' },
  { url: '/company-lists/:listId/rename' },
  { url: '/contacts/:contactId/archive' },
  { url: '/contacts/:contactId/unarchive' },
  { url: '/investments/opportunities/:opportunityId' },
  { url: '/investments/:investmentId/edit-history' },
  { url: '/omis/edit/payment-reconciliation' },
  { url: '/export/:exportId/edit' },
  { url: '/export/:exportId/delete' },
  { url: '/investments/projects/:investmentId/interactions' },
  { url: '/investments/projects/:projectId/evidence' },
  { url: '/investments/projects/:projectId/evidence/:evidenceId/delete' },
  {
    url: '/companies/:companyId/referrals/:referralId/interactions/create/:theme/:kind',
  },
  { url: '/companies/:companyId/interactions/create/:theme/:kind' },
  { url: '/investments/projects/create/investment-type/info/:anchor' },
  { url: '/investments/:investmentId/interactions/:interactionsId' },
  { url: '/my-pipeline/:pipelineId/edit' },
  { url: '/my-pipeline/:pipelineId/archive' },
  { url: '/my-pipeline/:pipelineId/unarchive' },
  { url: '/my-pipeline/:pipelineId/delete' },
  { url: '/companies/:companyId/exports/history/:countryId' },
  { url: '/companies/:companyId/referrals/:referralId/interactions' },
  { url: '/interactions/create' },
  { url: '/interactions/create/:theme/:kind' },
  { url: '/interactions/activeEvents' },
  { url: '/activeEvents/' },
  {
    url: '/investments/projects/:projectId/edit-associated/:associatedProjectId',
  },
  { url: '/export/:exportId/details' },
  { url: '/omis/:orderId/edit/lead-adviser/:adviserId' },
  { url: '/interactions/ess/:essInteractionId/details' },
  {
    url: '/companies/:companyId/account-management/objective/:objectiveId/edit',
  },
  {
    url: '/companies/:companyId/account-management/objective/:objectiveId/archive',
  },
  {
    url: '/investments/projects/:investmentId/propositions/:propositionId/abandon',
  },
  {
    url: '/investments/projects/:investmentId/propositions/:propositionId/document',
  },
  {
    url: '/investments/projects/:investmentId/propositions/:propositionId/document/:documentId/delete',
  },
  {
    url: '/investments/projects/:investmentId/propositions/:propositionId/complete',
  },
  { url: '/investments/projects/:investmentId/propositions/:propositionId' },
  { url: '/companies/:companyId/hierarchies/ghq/:globalHqId/add' },
  { url: '/companies/:companyId/hierarchies/ghq/remove' },
  { url: '/companies/:companyId' },
  { url: '/contacts/:contactId/interactions/:interactionId' },
  { url: '/contacts/:contactId/interactions/create' },
  { url: '/contacts/:contactId/interactions/create/:theme/:kind' },
  { url: '/contacts/:contactId/interactions/:interactionId/edit' },
  // API calls with redirect
  { url: '/company-lists/' }, // Redirects to homepage (which is tested)
  { url: '/tasks/:taskId/status-complete' },
  { url: '/tasks/:taskId/status-active' },
  { url: '/tasks/:taskId/archive' },
  { url: '/tasks/:taskId/unarchive' },
  // 501 errors
  { url: '/investments/projects/:projectId/edit-ukcompany/:companyId' },
  // Excluded urls
  { url: '/testing/' },
  { url: '/oauth/' },
  { url: '/oauth/callback/' },
  { url: '/oauth/sign-out/' },
  { url: '/exportwins/pending/' },
  { url: '/exportwins/rejected/' },
  { url: '/exportwins/:winId/edit' },
  { url: '/exportwins/:winId/success' },
  { url: '/companies/:companyId/exportwins/:winId/customer-feedback' },
  { url: '/companies/:companyId/export/:exportId/exportwins/create' },
  { url: '/companies/e59a2b0f-7d84-4de7-bc1e-f70339f4255f/overview' },
]
