export const DELETE_DOCUMENT_ID = 'deleteProjectDocument'
export const TASK_DELETE_PROJECT_DOCUMENT = 'TASK_DELETE_PROJECT_DOCUMENT'
export const TASK_ADD_PROJECT_DOCUMENT = 'TASK_ADD_PROJECT_DOCUMENT'
