export const TASK_EDIT_INVESTMENT_PROJECT_SUMMARY =
  'TASK_EDIT_INVESTMENT_PROJECT_SUMMARY'
export const TASK_EDIT_INVESTMENT_PROJECT_REQUIREMENTS =
  'TASK_EDIT_INVESTMENT_PROJECT_REQUIREMENTS'
export const TASK_EDIT_INVESTMENT_PROJECT_VALUE =
  'TASK_EDIT_INVESTMENT_PROJECT_VALUE'
export const TASK_EDIT_INVESTMENT_PROJECT_STATUS =
  'TASK_EDIT_INVESTMENT_PROJECT_VALUE'
export const TASK_UPDATE_INVESTMENT_PROJECT_STAGE =
  'TASK_UPDATE_INVESTMENT_PROJECT_STAGE'

export const state2props = (state) => {
  return { currentAdviserId: state.currentAdviserId }
}
