export const ID = 'reminders'

// Investment lists
export const TASK_GET_ESTIMATED_LAND_DATE_REMINDERS =
  'TASK_GET_ESTIMATED_LAND_DATE_REMINDERS'
export const TASK_DELETE_ESTIMATED_LAND_DATE_REMINDER =
  'TASK_DELETE_ESTIMATED_LAND_DATE_REMINDER'
export const TASK_GET_NEXT_ESTIMATED_LAND_DATE_REMINDER =
  'TASK_GET_NEXT_ESTIMATED_LAND_DATE_REMINDER'

export const TASK_GET_EXPORTS_NO_RECENT_INTERACTION_REMINDERS =
  'TASK_GET_EXPORTS_NO_RECENT_INTERACTION_REMINDERS'
export const TASK_DELETE_EXPORTS_NO_RECENT_INTERACTION_REMINDER =
  'TASK_DELETE_EXPORTS_NO_RECENT_INTERACTION_REMINDER'
export const TASK_GET_NEXT_EXPORTS_NO_RECENT_INTERACTION_REMINDERS =
  'TASK_GET_NEXT_EXPORTS_NO_RECENT_INTERACTION_REMINDERS'

export const TASK_GET_NO_RECENT_INTERACTION_REMINDERS =
  'TASK_GET_NO_RECENT_INTERACTION_REMINDERS'
export const TASK_DELETE_NO_RECENT_INTERACTION_REMINDER =
  'TASK_DELETE_NO_RECENT_INTERACTION_REMINDER'
export const TASK_GET_NEXT_NO_RECENT_INTERACTION_REMINDER =
  'TASK_GET_NEXT_NO_RECENT_INTERACTION_REMINDER'

// Outstanding propositions list
export const TASK_GET_OUTSTANDING_PROPOSITIONS_REMINDERS =
  'TASK_GET_OUTSTANDING_PROPOSITIONS_REMINDERS'

// Summary
export const TASK_GET_SUBSCRIPTION_SUMMARY = 'TASK_GET_SUBSCRIPTION_SUMMARY'

// Investment subscriptions
export const TASK_GET_ELD_REMINDER_SUBSCRIPTIONS =
  'TASK_GET_ELD_REMINDER_SUBSCRIPTIONS'
export const TASK_SAVE_ELD_REMINDER_SUBSCRIPTIONS =
  'TASK_SAVE_ELD_REMINDER_SUBSCRIPTIONS'
export const TASK_GET_NRI_REMINDER_SUBSCRIPTIONS =
  'TASK_GET_NRI_REMINDER_SUBSCRIPTIONS'
export const TASK_SAVE_NRI_REMINDER_SUBSCRIPTIONS =
  'TASK_SAVE_NRI_REMINDER_SUBSCRIPTIONS'

// Exports subscriptions
export const TASK_GET_EXPORT_NRI_REMINDER_SUBSCRIPTIONS =
  'TASK_GET_EXPORT_NRI_REMINDER_SUBSCRIPTIONS'
export const TASK_SAVE_EXPORT_NRI_REMINDER_SUBSCRIPTIONS =
  'TASK_SAVE_EXPORT_NRI_REMINDER_SUBSCRIPTIONS'
