export const TASK_GET_ALL_REMINDER_SUBSCRIPTIONS =
  'TASK_GET_ALL_REMINDER_SUBSCRIPTIONS'
export const TASK_GET_ELD_REMINDER_SUBSCRIPTIONS =
  'TASK_GET_ELD_REMINDER_SUBSCRIPTIONS'
export const TASK_SAVE_ELD_REMINDER_SUBSCRIPTIONS =
  'TASK_SAVE_ELD_REMINDER_SUBSCRIPTIONS'
export const TASK_GET_NRI_REMINDER_SUBSCRIPTIONS =
  'TASK_GET_NRI_REMINDER_SUBSCRIPTIONS'
export const TASK_SAVE_NRI_REMINDER_SUBSCRIPTIONS =
  'TASK_SAVE_NRI_REMINDER_SUBSCRIPTIONS'
export const TASK_GET_ESTIMATED_LAND_DATE_REMINDERS =
  'TASK_GET_ESTIMATED_LAND_DATE_REMINDERS'
export const TASK_GET_NO_RECENT_INTERACTION_REMINDERS =
  'TASK_GET_NO_RECENT_INTERACTION_REMINDERS'
