export const ID = 'pipeline'
export const TASK_GET_PIPELINE_BY_COMPANY = 'TASK_GET_PIPELINE_BY_COMPANY'

export const TASK_ADD_COMPANY_TO_PIPELINE = 'TASK_ADD_COMPANY_TO_PIPELINE'
export const TASK_GET_PIPELINE_ITEM = 'TASK_GET_PIPELINE_ITEM'
export const TASK_EDIT_PIPELINE_ITEM = 'TASK_EDIT_PIPELINE_ITEM'
export const TASK_ARCHIVE_PIPELINE_ITEM = 'TASK_ARCHIVE_PIPELINE_ITEM'
export const TASK_UNARCHIVE_PIPELINE_ITEM = 'TASK_UNARCHIVE_PIPELINE_ITEM'
export const TASK_DELETE_PIPELINE_ITEM = 'TASK_DELETE_PIPELINE_ITEM'

export const state2props = (state) => state[ID]
