export const AUTOMATIC_UPDATE = 'automaticUpdate'
export const NOT_SET = 'Not set'
export const YES = 'Yes'
export const NO = 'No'
export const ARCHIVED = 'Archived'
export const NOT_ARCHIVED = 'Not archived'
