const TOTAL_INVESTMENT_SOUGHT_FIELD_NAME = 'total_investment_sought'
const CURRENT_INVESTMENT_SECURED_FIELD_NAME = 'current_investment_secured'
const INVESTMENT_TYPES_FIELD_NAME = 'investment_types'
const ESTIMATED_RETURN_RATE_FIELD_NAME = 'estimated_return_rate'
const TIME_HORIZONS_FIELD_NAME = 'time_horizons'

module.exports = {
  TOTAL_INVESTMENT_SOUGHT_FIELD_NAME,
  CURRENT_INVESTMENT_SECURED_FIELD_NAME,
  INVESTMENT_TYPES_FIELD_NAME,
  ESTIMATED_RETURN_RATE_FIELD_NAME,
  TIME_HORIZONS_FIELD_NAME,
}
