const TOTAL_INVESTMENT_SOUGHT_FIELD_NAME = 'total_investment_sought'
const CURRENT_INVESTMENT_SECURED_FIELD_NAME = 'current_investment_secured'
const INVESTMENT_TYPES_FIELD_NAME = 'investment_types'
const ESTIMATED_RETURN_RATE_FIELD_NAME = 'estimated_return_rate'
const TIME_HORIZONS_FIELD_NAME = 'time_horizons'
const CLEARED_REFERENCE = '02d6fc9b-fbb9-4621-b247-d86f2487898e'
const ISSUES_IDENTIFIED_REFERENCE = '9beab8fc-1094-49b4-97d0-37bc7a9de631'
const STATUS_FIELD_NAME = 'status'

module.exports = {
  TOTAL_INVESTMENT_SOUGHT_FIELD_NAME,
  CURRENT_INVESTMENT_SECURED_FIELD_NAME,
  INVESTMENT_TYPES_FIELD_NAME,
  ESTIMATED_RETURN_RATE_FIELD_NAME,
  TIME_HORIZONS_FIELD_NAME,
  CLEARED_REFERENCE,
  ISSUES_IDENTIFIED_REFERENCE,
  STATUS_FIELD_NAME,
}
