export const TASK_GET_OPPORTUNITY_DETAILS = 'TASK_GET_OPPORTUNITY_DETAILS'
export const TASK_GET_OPPORTUNITY_DETAILS_METADATA =
  'TASK_GET_OPPORTUNITY_DETAILS_METADATA'
export const TASK_GET_OPPORTUNITY_REQUIREMENTS_METADATA =
  'TASK_GET_OPPORTUNITY_REQUIREMENTS_METADATA'
export const TASK_GET_OPPORTUNITY_STATUS_METADATA =
  'TASK_GET_OPPORTUNITY_STATUS_METADATA'

export const TASK_SAVE_OPPORTUNITY_DETAILS = 'TASK_SAVE_OPPORTUNITY_DETAILS'
export const TASK_SAVE_OPPORTUNITY_REQUIREMENTS =
  'TASK_SAVE_OPPORTUNITY_REQUIREMENTS'
export const TASK_SAVE_OPPORTUNITY_STATUS = 'TASK_SAVE_OPPORTUNITY_STATUS'

export const ID = 'opportunityDetails'
export const SAVED = 'edit-saved'

export const state2props = (state) => state[ID]
